Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,61 +14,61 @@ on:
       - '.github/workflows/main.yml'
       
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    # needs: test
+  # build:
+  #   runs-on: ubuntu-latest
+  #   # needs: test
 
-    steps:
-      - name: Check out
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Check out
+  #       uses: actions/checkout@v3
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #     - name: Login to Docker Hub
+  #       uses: docker/login-action@v3
+  #       with:
+  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Build and push image
-        env:
-          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-          IMAGE_TAG: ${{ github.sha }}
-        run: |
-          docker pull $DOCKERHUB_USERNAME/go-devops-test:latest
-          cd src
-          docker build -t "$DOCKERHUB_USERNAME/go-devops-test:latest" .
-          docker push "$DOCKERHUB_USERNAME/go-devops-test:latest"
+  #     - name: Build and push image
+  #       env:
+  #         DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
+  #         IMAGE_TAG: ${{ github.sha }}
+  #       run: |
+  #         docker pull $DOCKERHUB_USERNAME/go-devops-test:latest
+  #         cd src
+  #         docker build -t "$DOCKERHUB_USERNAME/go-devops-test:latest" .
+  #         docker push "$DOCKERHUB_USERNAME/go-devops-test:latest"
 
-  test:
-    runs-on: ubuntu-latest
-    needs: build
+  # test:
+  #   runs-on: ubuntu-latest
+  #   needs: build
     
-    steps:
-      - name: Check out
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Check out
+  #       uses: actions/checkout@v3
       
-      - name: Set up Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20
+  #     - name: Set up Node
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 20
       
-      - name: Install dependencies
-        run: npm install
-        working-directory: src
+  #     - name: Install dependencies
+  #       run: npm install
+  #       working-directory: src
         
-      - name: Test
-        run: |
-          if npm test; then
-            echo "test success"
-          else
-            echo "test failure"
-            exit 1
-          fi
-        working-directory: src
+  #     - name: Test
+  #       run: |
+  #         if npm test; then
+  #           echo "test success"
+  #         else
+  #           echo "test failure"
+  #           exit 1
+  #         fi
+  #       working-directory: src
       
 
   deploy:
       runs-on: ubuntu-latest
-      needs: [build, test]
+      # needs: [build, test]
       
       steps:
         - name: Deploy to Cloud Run
@@ -87,5 +87,5 @@ jobs:
           working-directory: src
           
         - name: Deploy
-          run: gcloud run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/go-devops-test:latest --platform managed --region us-west4 --allow-unauthenticated
+          run: gcloud run deploy $PROJECT_ID --image gcr.io/$PROJECT_ID/go-devops-test:latest --platform managed --region us-west4
           working-directory: src
