Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,4 +1,4 @@
-name: CI/CD Pipeline
+name: CI build
 
 on:
   push:
@@ -6,23 +6,49 @@ on:
       - master
 
 jobs:
-  build-and-deploy:
+  test:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout Repository
+      - name: Check out
         uses: actions/checkout@v2
-
-      - name: Set up Node.js
+      
+      - name: Set up Node
         uses: actions/setup-node@v2
         with:
           node-version: '14'
+      
+      - name: Install dependencies
+        run: npm install
+        working-directory: src
+        
+      - name: Test
+        run: |
+          if npm test; then
+            echo "test success"
+          else
+            echo "test failure"
+            exit 1
+          fi
+        working-directory: src
+      
+  build:
+    runs-on: ubuntu-latest
+    needs: test
 
-      - name: Build and Push Docker Image
+    steps:
+      - name: Check out
+        uses: actions/checkout@v2
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USER }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build and push image
         env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
-          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
         run: |
-          docker build -t $DOCKERHUB_USER/go-devops-test:latest .
-          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
-          docker push $DOCKERHUB_USER/go-devops-test:latest
+          docker build -t $DOCKERHUB_USERNAME/go-devops-testt:latest .
+          docker push $DOCKERHUB_USERNAME/go-devops-test:latest
