Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,37 +1,56 @@
-name: ci
+name: CI build
 
 on:
   push:
     branches:
-      - 'master'
+      - master
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    name: Build
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  test:
+    runs-on: ubuntu-latest
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+    steps:
+      - name: Check out
+        uses: actions/checkout@v2
+      
+      - name: Set up Node
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14'
+      
+      - name: Install dependencies
+        run: npm install
+        working-directory: src
+        
+      - name: Test
+        run: |
+          if npm test; then
+            echo "test success"
+          else
+            echo "test failure"
+            exit 1
+          fi
+        working-directory: src
+      
+  build:
+    runs-on: ubuntu-latest
+    needs: test
 
-      - name: Build image
-        env:
-          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-          IMAGE_TAG: ${{ github.sha }}
-        run: |
-          docker pull $DOCKERHUB_USERNAME/godenowl:base
-          cd src && docker build -t $DOCKERHUB_USERNAME/godenowl:$IMAGE_TAG -f Dockerfile .
+    steps:
+      - name: Check out
+        uses: actions/checkout@v2
 
-      - name: Push images to Docker Hub
-        env:
-          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-          IMAGE_TAG: ${{ github.sha }}
-        run: |
-          docker push $DOCKERHUB_USERNAME/godenowl:$IMAGE_TAG
-          docker tag $DOCKERHUB_USERNAME/godenowl:$IMAGE_TAG $DOCKERHUB_USERNAME/godenowl:latest
-          docker push $DOCKERHUB_USERNAME/godenowl:latest
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKER_HUB_USERNAME }}
+          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
+
+      - name: Build and push image
+        env:
+          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
+        run: |
+          docker build -t $DOCKERHUB_USERNAME/golden-owl-test:latest .
+          docker push $DOCKERHUB_USERNAME/golden-owl-test:latest
+
+
