Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,41 +1,55 @@
-name: Godenowl CICD
+name: CI build
 
 on:
-  workflow_dispatch:
-  push:
-    branches:
-      - 'master'
-    paths:
-      - 'src/**'
-      - '.github/workflows/cicd.yml'
+  push:
+    branches:
+      - 'master'
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    name: Build
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+  test:
+    runs-on: ubuntu-latest
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
+    steps:
+      - name: Check out
+        uses: actions/checkout@v3
+      
+      - name: Set up Node
+        uses: actions/setup-node@v3
+        with:
+          node-version: 20
+      
+      - name: Install dependencies
+        run: npm install
+        working-directory: src
+        
+      - name: Test
+        run: |
+          if npm test; then
+            echo "test success"
+          else
+            echo "test failure"
+            exit 1
+          fi
+        working-directory: src
+      
+  build:
+    runs-on: ubuntu-latest
+    needs: test
 
-      - name: Build image
-        env:
-          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-          IMAGE_TAG: ${{ github.sha }}
-        run: |
-          docker pull $DOCKERHUB_USERNAME/go-devops-test:latest
-          cd src && docker build -t $DOCKERHUB_USERNAME/go-devops-test:$IMAGE_TAG -f Dockerfile .
+    steps:
+      - name: Check out
+        uses: actions/checkout@v3
 
-      - name: Push images to Docker Hub
-        env:
-          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
-          IMAGE_TAG: ${{ github.sha }}
-        run: |
-          docker push $DOCKERHUB_USERNAME/go-devops-test:$IMAGE_TAG
-          docker tag $DOCKERHUB_USERNAME/go-devops-test:$IMAGE_TAG $DOCKERHUB_USERNAME/godenowl:latest
-          docker push $DOCKERHUB_USERNAME/go-devops-test:latest
+      - name: Login to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+      - name: Build and push image
+        env:
+          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
+        run: |
+          docker build -t $DOCKERHUB_USERNAME/go-devops-testt:latest .
+          docker push $DOCKERHUB_USERNAME/go-devops-test:latest
+
