Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,54 +1,89 @@
-name: CI build
+# name: CI build
+
+# on:
+#   push:
+#     branches:
+#       - 'master'
+
+# jobs:
+#   test:
+#     runs-on: ubuntu-latest
+
+#     steps:
+#       - name: Check out
+#         uses: actions/checkout@v3
+      
+#       - name: Set up Node
+#         uses: actions/setup-node@v3
+#         with:
+#           node-version: 20
+      
+#       - name: Install dependencies
+#         run: npm install
+#         working-directory: src
+        
+#       - name: Test
+#         run: |
+#           if npm test; then
+#             echo "test success"
+#           else
+#             echo "test failure"
+#             exit 1
+#           fi
+#         working-directory: src
+      
+#   build:
+#     runs-on: ubuntu-latest
+#     needs: test
+
+#     steps:
+#       - name: Check out
+#         uses: actions/checkout@v3
+
+#       - name: Login to Docker Hub
+#         uses: docker/login-action@v3
+#         with:
+#           username: ${{ secrets.DOCKERHUB_USERNAME }}
+#           password: ${{ secrets.DOCKERHUB_TOKEN }}
+
+#       - name: Build and push image
+#         env:
+#           DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
+#         run: |
+#           docker build -t $DOCKERHUB_USERNAME/go-devops-testt:latest .
+#           docker push $DOCKERHUB_USERNAME/go-devops-test:latest
+
+
+name: ci
 
 on:
   push:
     branches:
-      - 'master'
+      - 'main'
 
 jobs:
-  test:
+  docker:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Check out
-        uses: actions/checkout@v3
-      
-      - name: Set up Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 20
-      
-      - name: Install dependencies
-        run: npm install
-        working-directory: src
-        
-      - name: Test
-        run: |
-          if npm test; then
-            echo "test success"
-          else
-            echo "test failure"
-            exit 1
-          fi
-        working-directory: src
-      
-  build:
-    runs-on: ubuntu-latest
-    needs: test
-
-    steps:
-      - name: Check out
-        uses: actions/checkout@v3
-
-      - name: Login to Docker Hub
+      -
+        name: Checkout
+        uses: actions/checkout@v4
+      -
+        name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+      -
+        name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+      -
+        name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
-
-      - name: Build and push image
-        env:
-          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
-        run: |
-          docker build -t $DOCKERHUB_USERNAME/go-devops-testt:latest .
-          docker push $DOCKERHUB_USERNAME/go-devops-test:latest
+      -
+        name: Build and push
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          push: true
+          tags: user/app:latest
